### ISSUE TITLE
paper category

### ISSUE THREAD

**Issue by cranmer** [simulation-based-inference/simulation-based-inference.github.io#87]
Paper title:
Neural Importance Sampling for Rapid and Reliable Gravitational-Wave Inference

This paper should have a primary category of:

- "astro-ph": "Physics",

*Note: To simplify the list, several physics categories have been combined into one.

**Comment by JasonLo** [comment]
@cranmer Based on our previous conversation about categorization, we agreed to create a distinct category called "Astrophysics" on our website due to the large number of papers in that field. This is the current [mapping](https://github.com/simulation-based-inference/simulation-based-inference.github.io/blob/9579ece76b3fb4009e6a1727cb08fe5fc64f6276/backend/data/arxiv_group.json) for your reference. 

I just wanted to confirm if you would like us to merge `astro-ph` back into the broader category of "Physics"

After receiving clarification, I will proceed with making the necessary changes.

**Comment by JasonLo** [comment]
Addressed in #88
